// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4l1JVPlexVS9bNxA61q9_4gMLoPp4Yg',
    appId: '1:244894378898:web:f38829875ac1ad6a46af4b',
    messagingSenderId: '244894378898',
    projectId: 'newbie-project-8d539',
    authDomain: 'newbie-project-8d539.firebaseapp.com',
    storageBucket: 'newbie-project-8d539.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdeNdNC-oxhrrhaeQnYw1Kp-EpGQzIhxI',
    appId: '1:244894378898:android:60e12fb905baba2346af4b',
    messagingSenderId: '244894378898',
    projectId: 'newbie-project-8d539',
    storageBucket: 'newbie-project-8d539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHTHzwXEAiJFw4h1HByTB2ZthhqQIvE0',
    appId: '1:244894378898:ios:6f2fd66269e5ebfe46af4b',
    messagingSenderId: '244894378898',
    projectId: 'newbie-project-8d539',
    storageBucket: 'newbie-project-8d539.appspot.com',
    iosBundleId: 'com.example.newbieProjectCasio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHTHzwXEAiJFw4h1HByTB2ZthhqQIvE0',
    appId: '1:244894378898:ios:6f2fd66269e5ebfe46af4b',
    messagingSenderId: '244894378898',
    projectId: 'newbie-project-8d539',
    storageBucket: 'newbie-project-8d539.appspot.com',
    iosBundleId: 'com.example.newbieProjectCasio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ4l1JVPlexVS9bNxA61q9_4gMLoPp4Yg',
    appId: '1:244894378898:web:b09762f6e09acf1e46af4b',
    messagingSenderId: '244894378898',
    projectId: 'newbie-project-8d539',
    authDomain: 'newbie-project-8d539.firebaseapp.com',
    storageBucket: 'newbie-project-8d539.appspot.com',
  );
}
